export const WEATHER_REQUEST_START = 'WEATHER_REQUEST_START';
export const WEATHER_REQUEST_SUCCESS = 'WEATHER_REQUEST_SUCCESS';
export const WEATHER_REQUEST_ERROR = 'WEATHER_REQUEST_ERROR';
export const WEATHER_REQUEST_REFRESH = 'WEATHER_REQUEST_REFRESH';
export const DELETE_CITY = 'DELETE_CITY';